import AppKit
import CryptoKit

enum ClipboardHistoryCodec {
    static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")

    private static let ignoredTypes: Set<String> = [
        transientType.rawValue,
        concealedType.rawValue,
        autoGeneratedType.rawValue
    ]
    private static let supportedTypes: Set<String> = [
        NSPasteboard.PasteboardType.string.rawValue,
        NSPasteboard.PasteboardType.rtf.rawValue,
        NSPasteboard.PasteboardType.html.rawValue,
        NSPasteboard.PasteboardType.png.rawValue,
        NSPasteboard.PasteboardType.tiff.rawValue,
        NSPasteboard.PasteboardType.fileURL.rawValue,
        NSPasteboard.PasteboardType.URL.rawValue
    ]
    private static let imageTypes: Set<String> = [
        NSPasteboard.PasteboardType.png.rawValue,
        NSPasteboard.PasteboardType.tiff.rawValue
    ]

    static func candidate(
        from pasteboard: NSPasteboard,
        sourceApplication: NSRunningApplication?,
        capturedAt: Date = Date(),
        maximumPayloadBytes: Int
    ) -> ClipboardHistoryCandidate? {
        guard let pasteboardItems = pasteboard.pasteboardItems,
              !pasteboardItems.isEmpty
        else {
            return nil
        }

        let allTypeIdentifiers = Set(pasteboardItems.flatMap { $0.types.map(\.rawValue) })
        guard !shouldIgnore(typeIdentifiers: allTypeIdentifiers) else {
            return nil
        }

        let items = pasteboardItems.compactMap(payloadItem(from:))
        guard !items.isEmpty else {
            return nil
        }

        let originalPayload = ClipboardPayload(items: items)
        let boundedPayload = boundedPayload(originalPayload, maximumBytes: maximumPayloadBytes)
        guard let payloadData = encode(boundedPayload),
              !boundedPayload.items.isEmpty
        else {
            return nil
        }

        let description = describe(boundedPayload)
        let sourceName = sourceApplication?.localizedName
            ?? sourceApplication?.bundleIdentifier
            ?? AppStrings.text(.genericApplication)
        let searchParts = [
            description.searchableText,
            sourceName,
            sourceApplication?.bundleIdentifier ?? ""
        ].filter { !$0.isEmpty }

        return ClipboardHistoryCandidate(
            id: UUID(),
            capturedAt: capturedAt,
            sourceApplicationName: sourceName,
            sourceBundleIdentifier: sourceApplication?.bundleIdentifier,
            kind: description.kind,
            summary: description.summary,
            searchableText: searchParts.joined(separator: "\n"),
            fingerprint: fingerprint(for: payloadData),
            payloadData: payloadData,
            thumbnailData: thumbnailData(from: boundedPayload),
            byteCount: payloadData.count
        )
    }

    static func shouldIgnore(typeIdentifiers: Set<String>) -> Bool {
        !ignoredTypes.isDisjoint(with: typeIdentifiers)
    }

    static func decode(_ data: Data) -> ClipboardPayload? {
        try? PropertyListDecoder().decode(ClipboardPayload.self, from: data)
    }

    static func write(
        _ payload: ClipboardPayload,
        to pasteboard: NSPasteboard,
        sourceIdentifier: String
    ) -> Bool {
        let pasteboardItems = payload.items.compactMap { payloadItem -> NSPasteboardItem? in
            let item = NSPasteboardItem()
            var wroteRepresentation = false
            for representation in payloadItem.representations {
                let type = NSPasteboard.PasteboardType(representation.typeIdentifier)
                wroteRepresentation = item.setData(representation.data, forType: type)
                    || wroteRepresentation
            }
            return wroteRepresentation ? item : nil
        }
        guard !pasteboardItems.isEmpty else {
            return false
        }

        _ = pasteboardItems[0].setString(sourceIdentifier, forType: sourceType)
        pasteboard.clearContents()
        return pasteboard.writeObjects(pasteboardItems)
    }

    static func plainText(from payload: ClipboardPayload) -> String? {
        for item in payload.items {
            if let string = stringRepresentation(
                in: item,
                typeIdentifier: NSPasteboard.PasteboardType.string.rawValue
            ) {
                return string
            }
            if let richText = attributedString(in: item)?.string, !richText.isEmpty {
                return richText
            }
        }
        return nil
    }

    static func previewContent(
        record: ClipboardHistoryRecord,
        payload: ClipboardPayload
    ) -> ClipboardHistoryPreviewContent {
        let filePaths = payload.items.compactMap(fileURL(in:)).map(\.path)
        let imageData = payload.items
            .lazy
            .flatMap(\.representations)
            .first(where: { imageTypes.contains($0.typeIdentifier) })?
            .data
        let text = previewText(from: payload, excludingFileURLs: !filePaths.isEmpty)

        return ClipboardHistoryPreviewContent(
            record: record,
            text: text,
            imageData: imageData,
            filePaths: filePaths
        )
    }

    private static func payloadItem(from pasteboardItem: NSPasteboardItem) -> ClipboardPayloadItem? {
        let representations = pasteboardItem.types
            .filter { supportedTypes.contains($0.rawValue) }
            .compactMap { type -> ClipboardPayloadRepresentation? in
                guard let data = pasteboardItem.data(forType: type), !data.isEmpty else {
                    return nil
                }
                return ClipboardPayloadRepresentation(typeIdentifier: type.rawValue, data: data)
            }
            .sorted { lhs, rhs in
                lhs.typeIdentifier < rhs.typeIdentifier
            }
        return representations.isEmpty ? nil : ClipboardPayloadItem(representations: representations)
    }

    private static func boundedPayload(
        _ payload: ClipboardPayload,
        maximumBytes: Int
    ) -> ClipboardPayload {
        guard let encoded = encode(payload), encoded.count > maximumBytes else {
            return payload
        }

        let textAndURLItems = payload.items.compactMap { item -> ClipboardPayloadItem? in
            let representations = item.representations.filter {
                !imageTypes.contains($0.typeIdentifier)
            }
            return representations.isEmpty ? nil : ClipboardPayloadItem(representations: representations)
        }
        let fallback = ClipboardPayload(items: textAndURLItems)
        guard let encodedFallback = encode(fallback), encodedFallback.count <= maximumBytes else {
            return ClipboardPayload(items: [])
        }
        return fallback
    }

    private static func encode(_ payload: ClipboardPayload) -> Data? {
        let encoder = PropertyListEncoder()
        encoder.outputFormat = .binary
        return try? encoder.encode(payload)
    }

    private static func fingerprint(for data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }

    private static func describe(
        _ payload: ClipboardPayload
    ) -> (kind: ClipboardContentKind, summary: String, searchableText: String) {
        let fileURLs = payload.items.compactMap(fileURL(in:))
        if !fileURLs.isEmpty {
            let paths = fileURLs.map(\.path)
            let names = fileURLs.map(\.lastPathComponent)
            let summary = names.prefix(3).joined(separator: ", ")
                + (names.count > 3 ? " +\(names.count - 3)" : "")
            return (.files, summary, paths.joined(separator: "\n"))
        }

        if let imageSummary = firstImageDescription(in: payload) {
            return (.image, imageSummary, imageSummary)
        }

        let plainStrings = payload.items.compactMap {
            stringRepresentation(
                in: $0,
                typeIdentifier: NSPasteboard.PasteboardType.string.rawValue
            )
        }
        if let first = plainStrings.first {
            return (.text, summarized(first), plainStrings.joined(separator: "\n"))
        }

        let richStrings = payload.items.compactMap { attributedString(in: $0)?.string }
        if let first = richStrings.first {
            return (.richText, summarized(first), richStrings.joined(separator: "\n"))
        }

        let URLs = payload.items.compactMap(resourceURL(in:))
        if let first = URLs.first {
            let strings = URLs.map(\.absoluteString)
            return (.url, summarized(first.absoluteString), strings.joined(separator: "\n"))
        }

        return (.text, AppStrings.text(.clipboardUnknownContent), "")
    }

    private static func summarized(_ value: String) -> String {
        let flattened = value
            .replacingOccurrences(of: "\r\n", with: "\n")
            .replacingOccurrences(of: "\n", with: " ")
            .trimmingCharacters(in: .whitespacesAndNewlines)
        if flattened.count <= 180 {
            return flattened
        }
        return String(flattened.prefix(177)) + "..."
    }

    private static func stringRepresentation(
        in item: ClipboardPayloadItem,
        typeIdentifier: String
    ) -> String? {
        guard let data = item.representations.first(where: {
            $0.typeIdentifier == typeIdentifier
        })?.data else {
            return nil
        }
        return String(data: data, encoding: .utf8)?
            .trimmingCharacters(in: CharacterSet(charactersIn: "\0"))
    }

    private static func attributedString(in item: ClipboardPayloadItem) -> NSAttributedString? {
        if let data = item.representations.first(where: {
            $0.typeIdentifier == NSPasteboard.PasteboardType.rtf.rawValue
        })?.data {
            return try? NSAttributedString(
                data: data,
                options: [.documentType: NSAttributedString.DocumentType.rtf],
                documentAttributes: nil
            )
        }
        if let data = item.representations.first(where: {
            $0.typeIdentifier == NSPasteboard.PasteboardType.html.rawValue
        })?.data {
            return try? NSAttributedString(
                data: data,
                options: [.documentType: NSAttributedString.DocumentType.html],
                documentAttributes: nil
            )
        }
        return nil
    }

    private static func fileURL(in item: ClipboardPayloadItem) -> URL? {
        URL(string: stringRepresentation(
            in: item,
            typeIdentifier: NSPasteboard.PasteboardType.fileURL.rawValue
        ) ?? "").flatMap { $0.isFileURL ? $0 : nil }
    }

    private static func resourceURL(in item: ClipboardPayloadItem) -> URL? {
        URL(string: stringRepresentation(
            in: item,
            typeIdentifier: NSPasteboard.PasteboardType.URL.rawValue
        ) ?? "")
    }

    private static func previewText(
        from payload: ClipboardPayload,
        excludingFileURLs: Bool
    ) -> String? {
        var values: [String] = []
        for item in payload.items {
            if let string = stringRepresentation(
                in: item,
                typeIdentifier: NSPasteboard.PasteboardType.string.rawValue
            ), !string.isEmpty {
                values.append(string)
                continue
            }
            if let richText = attributedString(in: item)?.string, !richText.isEmpty {
                values.append(richText)
                continue
            }
            if !excludingFileURLs, let URL = resourceURL(in: item) {
                values.append(URL.absoluteString)
            }
        }
        guard !values.isEmpty else {
            return nil
        }
        return values.joined(separator: "\n")
    }

    private static func firstImageDescription(in payload: ClipboardPayload) -> String? {
        guard payload.items.contains(where: { item in
            item.representations.contains(where: { imageTypes.contains($0.typeIdentifier) })
        }) else {
            return nil
        }
        return payload.items.count > 1
            ? AppStrings.format(.clipboardImageCount, payload.items.count)
            : AppStrings.text(.clipboardImage)
    }

    private static func thumbnailData(from payload: ClipboardPayload) -> Data? {
        guard let data = payload.items
            .lazy
            .flatMap(\.representations)
            .first(where: { imageTypes.contains($0.typeIdentifier) })?
            .data,
              let image = NSImage(data: data)
        else {
            return nil
        }

        let maximumDimension: CGFloat = 240
        let scale = min(
            maximumDimension / max(image.size.width, 1),
            maximumDimension / max(image.size.height, 1),
            1
        )
        let size = NSSize(
            width: max(1, image.size.width * scale),
            height: max(1, image.size.height * scale)
        )
        let output = NSImage(size: size)
        output.lockFocus()
        image.draw(
            in: NSRect(origin: .zero, size: size),
            from: .zero,
            operation: .copy,
            fraction: 1
        )
        output.unlockFocus()

        guard let tiff = output.tiffRepresentation,
              let bitmap = NSBitmapImageRep(data: tiff)
        else {
            return nil
        }
        return bitmap.representation(using: .png, properties: [:])
    }
}
